name: deployment pipeline
on:
  push:
    branches:
      - main

jobs:
  setup_job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: install dependencies
        run: npm install

      - name: linting
        run: npm run lint

      - name: building
        run: npm run build

      - name: deploying
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          npm run deploy
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

