name: deployment pipeline
on:
  push:
    branches:
      - main

jobs:
  setup_job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: install dependencies
        run: npm install

      - name: linting
        run: npm run lint

      - name: deploying
        env:
          GITHUB_TOKEN: ${{secrets.GH_PAGES}}
        run: npm run deploy
